name: Call Codegraph document generation API

on: 
  push:
    branches:
      - main

jobs:
  send_api_request:
    runs-on: ubuntu-latest
    steps:
      - name: Call Codegraph document generation API
        shell: bash
        env:
          CODEGRAPH_API_TOKEN: ${{ secrets.CODEGRAPH_API_TOKEN }}
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          url="https://api.codegraph.co.jp/repos/${GITHUB_REPOSITORY}/branches/${branch_name}/update"
          echo "${url}"

          http_status_code=$(curl -s -o /dev/null -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer ${CODEGRAPH_API_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{}' \
            "${url}")

          if [ $http_status_code -ge 200 ] && [ $http_status_code -lt 400 ]; then
            echo "Success: status code is in the 200-300 range."
          else
            echo "Error: status code $http_status_code is not in the 200-300 range. Failing."
            exit 1
          fi
